<?php

return [
    'gender'         => [
        'title'   => 'Kjønn',
        'slug' => 'gender',
        'options' => [
            'Kvinne',
            'Mann'
        ]
    ],
    'age'            => [
        'title'   => 'Alder',
        'slug' => 'age',
        'options' => [
            '0-18',
            '19-25',
            '26-35',
            '36-45',
            '46-55',
            '56-65',
            '66-75',
            '76+'
        ]
    ],
    'income'         => [
        'title'   => 'Inntekt',
        'slug' => 'income',
        'options' => [
            '0 - 150.000',
            '150.000 - 250.000',
            '250.000 - 350.000',
            '350.000 - 450.000',
            '450.000 - 550.000',
            '550.000 - 650.000',
        ]
    ],
    'last_vote'      => [
        'title'   => 'Stemte ved forrige valg',
        'slug' => 'last_vote',
        'options' => [
            'Arbeiderpartiet',
            'Fremskrittspartiet',
            'Høyre',
            'Kristelig Folkeparti',
            'Miljøpartiet De Grønne',
            'Senterpartiet',
            'Sosialistisk Venstreparti',
            'Venstre',
            'Andre',
            'Stemte ikke',
        ]
    ],
    'will_vote'      => [
        'title'   => 'Vil stemme nå',
        'slug' => 'will_vote',
        'options' => [
            'Arbeiderpartiet',
            'Fremskrittspartiet',
            'Høyre',
            'Kristelig Folkeparti',
            'Miljøpartiet De Grønne',
            'Senterpartiet',
            'Sosialistisk Venstreparti',
            'Venstre',
            'Andre',
            'Stemte ikke',
        ]
    ],
    'political_view' => [
        'title'   => 'Politisk syn',
        'slug' => 'political_view',
        'options' => [
            'Liberalist',
            'Konservativ',
            'Kristendemokrat',
            'Sosialliberal',
            'Sosialdemokrat',
            'Sosialist',
            'Kommunist',
            'Anarkist',
            'Andre'
        ]
    ],
    'region'         => [
        'title'   => 'Fylke',
        'slug' => 'region',
        'options' => [
            'Akershus'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Vestby',
                    'Ski',
                    'Ås',
                    'Frogn',
                    'Nesodden',
                    'Oppegård',
                    'Bærum',
                    'Asker',
                    'Aurskog-Høland',
                    'Sørum',
                    'Fet',
                    'Rælingen',
                    'Enebakk',
                    'Lørenskog',
                    'Skedsmo',
                    'Nittedal',
                    'Gjerdrum',
                    'Ullensaker',
                    'Nes',
                    'Eidsvoll',
                    'Nannestad',
                    'Hurdal',
                ]
            ],
            'Aust-Agder'       => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Risør',
                    'Grimstad',
                    'Arendal',
                    'Gjerstad',
                    'Vegårshei',
                    'Tvedestrand',
                    'Froland',
                    'Lillesand',
                    'Birkenes',
                    'Åmli',
                    'Iveland',
                    'Evje og Hornnes',
                    'Bygland',
                    'Valle',
                    'Bykle',
                ]
            ],
            'Buskerud'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Drammen',
                    'Kongsberg',
                    'Ringerike',
                    'Hole',
                    'Flå',
                    'Nes',
                    'Gol',
                    'Hemsedal',
                    'Ål',
                    'Hol',
                    'Sigdal',
                    'Krødsherad',
                    'Modum',
                    'Øvre Eiker',
                    'Nedre Eiker',
                    'Lier',
                    'Røyken',
                    'Hurum',
                    'Flesberg',
                    'Rollag',
                    'Nore og Uvdal',
                ]
            ],
            'Finmark'          => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Vardø',
                    'Vadsø',
                    'Hammerfest',
                    'Kautokeino',
                    'Alta',
                    'Loppa',
                    'Hasvik',
                    'Kvalsund',
                    'Måsøy',
                    'Nordkapp',
                    'Porsanger',
                    'Karasjok',
                    'Lebesby',
                    'Gamvik',
                    'Berlevåg',
                    'Tana',
                    'Nesseby',
                    'Båtsfjord',
                    'Sør-Varanger',
                ]
            ],
            'Hedmark'          => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Kongsvinger',
                    'Hamar',
                    'Ringsaker',
                    'Løten',
                    'Stange',
                    'Nord-Odal',
                    'Sør-Odal',
                    'Eidskog',
                    'Grue',
                    'Åsnes',
                    'Våler',
                    'Elverum',
                    'Trysil',
                    'Åmot',
                    'Stor-Elvdal',
                    'Rendalen',
                    'Engerdal',
                    'Tolga',
                    'Tynset',
                    'Alvdal',
                    'Folldal',
                    'Os',
                ]
            ],
            'Hordaland'        => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Bergen',
                    'Etne',
                    'Sveio',
                    'Bømlo',
                    'Stord',
                    'Fitjar',
                    'Tysnes',
                    'Kvinnherad',
                    'Jondal',
                    'Odda',
                    'Ullensvang',
                    'Eidfjord',
                    'Ulvik',
                    'Granvin',
                    'Voss',
                    'Kvalm',
                    'Fusa',
                    'Samnanger',
                    'Os',
                    'Austevoll',
                    'Sund',
                    'Fjell',
                    'Askøy',
                    'Vaksdal',
                    'Modalen',
                    'Osterøy',
                    'Meland',
                    'Øygarden',
                    'Radøy',
                    'Lindås',
                    'Austrheim',
                    'Fedje',
                    'Masfjorden',
                ]
            ],
            'Møre og Romsdal'  => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Molde',
                    'Ålesund',
                    'Kristiansund',
                    'Vanylven',
                    'Sande',
                    'Herøy',
                    'Ulstein',
                    'Hareid',
                    'Volda',
                    'Ørsta',
                    'Ørskog',
                    'Norddal',
                    'Stranda',
                    'Stordal',
                    'Sykkylven',
                    'Skodje',
                    'Sula',
                    'Giske',
                    'Haram',
                    'Vestnes',
                    'Rauma',
                    'Nesset',
                    'Midsund',
                    'Sandøy',
                    'Aukra',
                    'Fræna',
                    'Eide',
                    'Alverøy',
                    'Gjemnes',
                    'Tingvoll',
                    'Sunndal',
                    'Surnadal',
                    'Rindal',
                    'Halsa',
                    'Smøla',
                    'Aura',
                ]
            ],
            'Nordland'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Bodø',
                    'Narvik',
                    'Bindal',
                    'Sømna',
                    'Brønnøy',
                    'Vega',
                    'Vevelstad',
                    'Herøy',
                    'Alstahaug',
                    'Leirfjord',
                    'Vefsn',
                    'Grane',
                    'Hatfjelldal',
                    'Dønna',
                    'Nesna',
                    'Hemnes',
                    'Rana',
                    'Lurøy',
                    'Træna',
                    'Rødøy',
                    'Meløy',
                    'Gildeskål',
                    'Beiarn',
                    'Saltdal',
                    'Fauske',
                    'Sørfold',
                    'Steigen',
                    'Hamarøy',
                    'Tysfjord',
                    'Lødingen',
                    'Tjeldsund',
                    'Evenes',
                    'Ballangen',
                    'Røst',
                    'Værøy',
                    'Flakstad',
                    'Vestvågøy',
                    'Vågan',
                    'Hadsel',
                    'Bø',
                    'Øksnes',
                    'Sortland',
                    'Andøy',
                    'Moskenes',
                ]
            ],
            'Nord-Trøndelag'   => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Steinkjer',
                    'Namsos',
                    'Meråker',
                    'Stjørdal',
                    'Frosta',
                    'Leksvik',
                    'Levanger',
                    'Verdal',
                    'Verran',
                    'Nemdalseid',
                    'Snåsa',
                    'Lierne',
                    'Røyrvik',
                    'Namsskogan',
                    'Grong',
                    'Høylandet',
                    'Overhalla',
                    'Fosnes',
                    'Flatlanger',
                    'Vikna',
                    'Nærøy',
                    'Leka',
                    'Inderøy',

                ]
            ],
            'Oppland'          => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Lillehammer',
                    'Gjøvik',
                    'Dovre',
                    'Lesja',
                    'Skjåk',
                    'Lom',
                    'Vågå',
                    'Nord-Fron',
                    'Sel',
                    'Sør-Fron',
                    'Ringebu',
                    'Øyer',
                    'Gausdal',
                    'Østre Toten',
                    'Vestre Toten',
                    'Jevnaker',
                    'Lunner',
                    'Gran',
                    'Søndre Land',
                    'Nordre Land',
                    'Sør-Aurdal',
                    'Etnedal',
                    'Nord-Aurdal',
                    'Vestre Slidre',
                    'Øystre Slidre',
                    'Vang',
                ]
            ],
            'Oslo'             => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Oslo',
                ]
            ],
            'Rogaland'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Eigersund',
                    'Sandes',
                    'Stavanger',
                    'Haugesund',
                    'Sokndal',
                    'Lund',
                    'Bjerkreim',
                    'Hå',
                    'Klepp',
                    'Time',
                    'Gjesdal',
                    'Sola',
                    'Randaberg',
                    'Forsand',
                    'Strand',
                    'Hjelmeland',
                    'Suldal',
                    'Sauda',
                    'Finnøy',
                    'Rennesøy',
                    'Kvitsøy',
                    'Bokn',
                    'Tysvær',
                    'Karmøy',
                    'Utsira',
                    'Vindafjord',
                ]
            ],
            'Sogn og Fjordane' => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Flora',
                    'Gulen',
                    'Solund',
                    'Hyllestad',
                    'Høyanger',
                    'Vik',
                    'Balestrand',
                    'Leikanger',
                    'Sogndal',
                    'Aurland',
                    'Lærdal',
                    'Årdal',
                    'Luster',
                    'Askvoll',
                    'Fjaler',
                    'Gaular',
                    'Jølster',
                    'Førde',
                    'Naustad',
                    'Bremanger',
                    'Vågsøy',
                    'Selje',
                    'Eid',
                    'Hornindal',
                    'Gloppen',
                    'Stryn',
                ]
            ],
            'Sør-Trøndelag'    => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Trondheim',
                    'Hemne',
                    'Snillfjord',
                    'Hitra',
                    'Frøya',
                    'Ørland',
                    'Agdenes',
                    'Rissa',
                    'Bjugn',
                    'Åsfjord',
                    'Roan',
                    'Osen',
                    'Oppdal',
                    'Rennebu',
                    'Meldal',
                    'Orkdal',
                    'Røros',
                    'Holtålen',
                    'Midtre Gauldal',
                    'Melhus',
                    'Skaun',
                    'Klæbu',
                    'Malvik',
                    'Selbu',
                    'Tydal',
                ]
            ],
            'Telemark'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Porsgrunn',
                    'Skien',
                    'Notodden',
                    'Siljan',
                    'Bamble',
                    'Kragerø',
                    'Drangedal',
                    'Nome',
                    'Bø',
                    'Sauherad',
                    'Tinn',
                    'Hjartdal',
                    'Selfjord',
                    'Kviteseid',
                    'Nissedal',
                    'Fyresdal',
                    'Tokke',
                    'Vinje',
                ]
            ],
            'Troms'            => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Tromsø',
                    'Harstad',
                    'Kvæfjord',
                    'Skånland',
                    'Ibestad',
                    'Gratangen',
                    'Lavanger',
                    'Bardu',
                    'Salangen',
                    'Målselv',
                    'Sørreisa',
                    'Dyrøs',
                    'Tranøy',
                    'Tosken',
                    'Berg',
                    'Lenvik',
                    'Balfjord',
                    'Karsløy',
                    'Lyngen',
                    'Storfjord',
                    'Kåfjord',
                    'Skjerøy',
                    'Nordreisa',
                    'Kvænangen',
                ]
            ],
            'Vest-Agder'       => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Kristiansand',
                    'Mandal',
                    'Farsund',
                    'Flekkefjord',
                    'Vennesla',
                    'Songdal',
                    'Søgne',
                    'Marnedal',
                    'Åseral',
                    'Audendal',
                    'Lindesnes',
                    'Lyngdal',
                    'Hægebostad',
                    'Kvinnesdal',
                    'Sirdal',
                ]
            ],
            'Vestfold'         => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Horten',
                    'Holmestrand',
                    'Tønsberg',
                    'Sandefjord',
                    'Larvik',
                    'Svelvik',
                    'Sande',
                    'Hof',
                    'Re',
                    'Andebu',
                    'Stokke',
                    'Nøtterøy',
                    'Tjøme',
                    'Lardal',
                ]
            ],
            'Østfold'          => [
                'title'   => 'Kommune',
                'slug'    => 'municipality',
                'options' => [
                    'Halden',
                    'Moss',
                    'Sarpsborg',
                    'Fredrikstad',
                    'Hvaler',
                    'Aremark',
                    'Marker',
                    'Rømskog',
                    'Trøgstad',
                    'Spydeberg',
                    'Askim',
                    'Eidsberg',
                    'Skiptvet',
                    'Rakkestad',
                    'Råde',
                    'Rygge',
                    'Våler',
                    'Hobøl',
                ]
            ],
        ]
    ]
];